package demo.delivery_project.common.constant;

public interface PermissionConstants {
    String USER_CREATE = "USER_CREATE";
    String USER_READ = "USER_READ ";
    String USER_UPDATE = "USER_UPDATE";
    String USER_DELETE = "USER_DELETE";
    String GET_USERS = "GET_USERS";
    String SET_CARRIER_REGIONS = "SET_CARRIER_REGIONS";

    String ROLE_CREATE = "ROLE_CREATE";
    String ROLE_READ = "ROLE_READ";
    String ROLE_UPDATE = "ROLE_UPDATE";
    String ROLE_DELETE = "ROLE_DELETE";
    String GET_ROLES = "GET_ROLES";

    String PRODUCT_CREATE = "PRODUCT_CREATE";
    String PRODUCT_READ = "PRODUCT_READ";
    String PRODUCT_UPDATE = "PRODUCT_UPDATE";
    String PRODUCT_DELETE = "PRODUCT_DELETE";
    String GET_USER_PRODUCTS = "GET_USER_PRODUCTS";
    String GET_OWN_PRODUCTS = "GET_OWN_PRODUCTS";

    String OFFER_CREATE = "OFFER_CREATE";
    String OFFER_READ = "OFFER_READ";
    String OFFER_UPDATE = "OFFER_UPDATE";
    String OFFER_DELETE = "OFFER_DELETE";
    String GET_USER_OFFERS = "GET_USER_OFFERS";
    String GET_OWN_OFFERS = "GET_OWN_OFFERS";

    String REQUEST_CREATE = "REQUEST_CREATE";
    String REQUEST_READ = "REQUEST_READ";
    String REQUEST_UPDATE = "REQUEST_UPDATE";
    String REQUEST_DELETE = "REQUEST_DELETE";
    String GET_USER_REQUESTS = "GET_USER_REQUESTS";
    String GET_OWN_REQUESTS = "GET_OWN_REQUESTS";

    String TRANSACTION_CREATE = "TRANSACTION_CREATE";
    String TRANSACTION_READ = "TRANSACTION_READ";
    String TRANSACTION_UPDATE = "TRANSACTION_UPDATE";
    String TRANSACTION_DELETE = "TRANSACTION_DELETE";
    String EVALUATE_TRANSACTION = "EVALUATE_TRANSACTION";
    String GET_USER_TRANSACTIONS = "GET_USER_TRANSACTIONS";
    String GET_OWN_TRANSACTIONS = "GET_OWN_TRANSACTIONS";

    String REGION_CREATE = "REGION_CREATE";
    String REGION_READ = "REGION_READ";
    String REGION_UPDATE = "REGION_UPDATE";
    String REGION_DELETE = "REGION_DELETE";
    String GET_REGIONS_AND_PLACES = "GET_REGIONS_AND_PLACES";

    String PLACE_CREATE = "PLACE_CREATE";
    String PLACE_READ = "PLACE_READ";
    String PLACE_UPDATE = "PLACE_UPDATE";
    String PLACE_DELETE = "PLACE_DELETE";

    String STATISTICS = "STATISTICS";
}
