/*
 * This file is generated by jOOQ.
 */
package demo.delivery_project.jooq.tables.records;


import demo.delivery_project.jooq.tables.Offers;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OffersRecord extends UpdatableRecordImpl<OffersRecord> implements Record7<UUID, UUID, String, String, String, LocalDateTime, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.offers.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.offers.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.offers.product_id</code>.
     */
    public void setProductId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.offers.product_id</code>.
     */
    public UUID getProductId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.offers.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.offers.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.offers.place_name</code>.
     */
    public void setPlaceName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.offers.place_name</code>.
     */
    public String getPlaceName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.offers.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.offers.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.offers.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.offers.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.offers.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.offers.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, UUID, String, String, String, LocalDateTime, UUID> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, UUID, String, String, String, LocalDateTime, UUID> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Offers.OFFERS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Offers.OFFERS.PRODUCT_ID;
    }

    @Override
    public Field<String> field3() {
        return Offers.OFFERS.CODE;
    }

    @Override
    public Field<String> field4() {
        return Offers.OFFERS.PLACE_NAME;
    }

    @Override
    public Field<String> field5() {
        return Offers.OFFERS.STATUS;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Offers.OFFERS.CREATED_AT;
    }

    @Override
    public Field<UUID> field7() {
        return Offers.OFFERS.CREATED_BY;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getProductId();
    }

    @Override
    public String component3() {
        return getCode();
    }

    @Override
    public String component4() {
        return getPlaceName();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public UUID component7() {
        return getCreatedBy();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getProductId();
    }

    @Override
    public String value3() {
        return getCode();
    }

    @Override
    public String value4() {
        return getPlaceName();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public UUID value7() {
        return getCreatedBy();
    }

    @Override
    public OffersRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public OffersRecord value2(UUID value) {
        setProductId(value);
        return this;
    }

    @Override
    public OffersRecord value3(String value) {
        setCode(value);
        return this;
    }

    @Override
    public OffersRecord value4(String value) {
        setPlaceName(value);
        return this;
    }

    @Override
    public OffersRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public OffersRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public OffersRecord value7(UUID value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public OffersRecord values(UUID value1, UUID value2, String value3, String value4, String value5, LocalDateTime value6, UUID value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OffersRecord
     */
    public OffersRecord() {
        super(Offers.OFFERS);
    }

    /**
     * Create a detached, initialised OffersRecord
     */
    public OffersRecord(UUID id, UUID productId, String code, String placeName, String status, LocalDateTime createdAt, UUID createdBy) {
        super(Offers.OFFERS);

        setId(id);
        setProductId(productId);
        setCode(code);
        setPlaceName(placeName);
        setStatus(status);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }
}
