/*
 * This file is generated by jOOQ.
 */
package demo.delivery_project.jooq.tables.records;


import demo.delivery_project.jooq.tables.Places;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlacesRecord extends UpdatableRecordImpl<PlacesRecord> implements Record4<UUID, String, UUID, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.places.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.places.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.places.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.places.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.places.region_id</code>.
     */
    public void setRegionId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.places.region_id</code>.
     */
    public UUID getRegionId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.places.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.places.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, String, UUID, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, String, UUID, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Places.PLACES.ID;
    }

    @Override
    public Field<String> field2() {
        return Places.PLACES.NAME;
    }

    @Override
    public Field<UUID> field3() {
        return Places.PLACES.REGION_ID;
    }

    @Override
    public Field<Boolean> field4() {
        return Places.PLACES.IS_DELETED;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UUID component3() {
        return getRegionId();
    }

    @Override
    public Boolean component4() {
        return getIsDeleted();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public UUID value3() {
        return getRegionId();
    }

    @Override
    public Boolean value4() {
        return getIsDeleted();
    }

    @Override
    public PlacesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public PlacesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PlacesRecord value3(UUID value) {
        setRegionId(value);
        return this;
    }

    @Override
    public PlacesRecord value4(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public PlacesRecord values(UUID value1, String value2, UUID value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlacesRecord
     */
    public PlacesRecord() {
        super(Places.PLACES);
    }

    /**
     * Create a detached, initialised PlacesRecord
     */
    public PlacesRecord(UUID id, String name, UUID regionId, Boolean isDeleted) {
        super(Places.PLACES);

        setId(id);
        setName(name);
        setRegionId(regionId);
        setIsDeleted(isDeleted);
        resetChangedOnNotNull();
    }
}
