/*
 * This file is generated by jOOQ.
 */
package demo.delivery_project.jooq.tables.records;


import demo.delivery_project.jooq.tables.Products;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductsRecord extends UpdatableRecordImpl<ProductsRecord> implements Record7<UUID, String, String, Double, UUID, LocalDateTime, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.products.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.products.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.products.name</code>. Descriptive name of the
     * product
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.products.name</code>. Descriptive name of the
     * product
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.products.code</code>. Unique product code
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.products.code</code>. Unique product code
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.products.price</code>.
     */
    public void setPrice(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.products.price</code>.
     */
    public Double getPrice() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.products.image_id</code>.
     */
    public void setImageId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.products.image_id</code>.
     */
    public UUID getImageId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.products.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.products.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.products.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.products.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, String, String, Double, UUID, LocalDateTime, UUID> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, String, String, Double, UUID, LocalDateTime, UUID> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Products.PRODUCTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Products.PRODUCTS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Products.PRODUCTS.CODE;
    }

    @Override
    public Field<Double> field4() {
        return Products.PRODUCTS.PRICE;
    }

    @Override
    public Field<UUID> field5() {
        return Products.PRODUCTS.IMAGE_ID;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Products.PRODUCTS.CREATED_AT;
    }

    @Override
    public Field<UUID> field7() {
        return Products.PRODUCTS.CREATED_BY;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getCode();
    }

    @Override
    public Double component4() {
        return getPrice();
    }

    @Override
    public UUID component5() {
        return getImageId();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public UUID component7() {
        return getCreatedBy();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getCode();
    }

    @Override
    public Double value4() {
        return getPrice();
    }

    @Override
    public UUID value5() {
        return getImageId();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public UUID value7() {
        return getCreatedBy();
    }

    @Override
    public ProductsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ProductsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProductsRecord value3(String value) {
        setCode(value);
        return this;
    }

    @Override
    public ProductsRecord value4(Double value) {
        setPrice(value);
        return this;
    }

    @Override
    public ProductsRecord value5(UUID value) {
        setImageId(value);
        return this;
    }

    @Override
    public ProductsRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ProductsRecord value7(UUID value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public ProductsRecord values(UUID value1, String value2, String value3, Double value4, UUID value5, LocalDateTime value6, UUID value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(UUID id, String name, String code, Double price, UUID imageId, LocalDateTime createdAt, UUID createdBy) {
        super(Products.PRODUCTS);

        setId(id);
        setName(name);
        setCode(code);
        setPrice(price);
        setImageId(imageId);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }
}
