/*
 * This file is generated by jOOQ.
 */
package demo.delivery_project.jooq.tables.records;


import demo.delivery_project.jooq.tables.Regions;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegionsRecord extends UpdatableRecordImpl<RegionsRecord> implements Record3<UUID, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.regions.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.regions.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.regions.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.regions.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.regions.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.regions.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, String, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Regions.REGIONS.ID;
    }

    @Override
    public Field<String> field2() {
        return Regions.REGIONS.NAME;
    }

    @Override
    public Field<Boolean> field3() {
        return Regions.REGIONS.IS_DELETED;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Boolean component3() {
        return getIsDeleted();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Boolean value3() {
        return getIsDeleted();
    }

    @Override
    public RegionsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public RegionsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public RegionsRecord value3(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public RegionsRecord values(UUID value1, String value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegionsRecord
     */
    public RegionsRecord() {
        super(Regions.REGIONS);
    }

    /**
     * Create a detached, initialised RegionsRecord
     */
    public RegionsRecord(UUID id, String name, Boolean isDeleted) {
        super(Regions.REGIONS);

        setId(id);
        setName(name);
        setIsDeleted(isDeleted);
        resetChangedOnNotNull();
    }
}
