/*
 * This file is generated by jOOQ.
 */
package demo.delivery_project.jooq.tables.records;


import demo.delivery_project.jooq.tables.Transactions;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionsRecord extends UpdatableRecordImpl<TransactionsRecord> implements Record9<UUID, Short, String, String, String, String, LocalDateTime, LocalDateTime, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.transactions.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.transactions.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.transactions.score</code>.
     */
    public void setScore(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.transactions.score</code>.
     */
    public Short getScore() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>public.transactions.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.transactions.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.transactions.carrier_username</code>.
     */
    public void setCarrierUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.transactions.carrier_username</code>.
     */
    public String getCarrierUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.transactions.request_code</code>.
     */
    public void setRequestCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.transactions.request_code</code>.
     */
    public String getRequestCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.transactions.offer_code</code>.
     */
    public void setOfferCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.transactions.offer_code</code>.
     */
    public String getOfferCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.transactions.perform_time</code>. The courier
     * completes the transaction after delivering the product
     */
    public void setPerformTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.transactions.perform_time</code>. The courier
     * completes the transaction after delivering the product
     */
    public LocalDateTime getPerformTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.transactions.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.transactions.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.transactions.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.transactions.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<UUID, Short, String, String, String, String, LocalDateTime, LocalDateTime, UUID> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<UUID, Short, String, String, String, String, LocalDateTime, LocalDateTime, UUID> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Transactions.TRANSACTIONS.ID;
    }

    @Override
    public Field<Short> field2() {
        return Transactions.TRANSACTIONS.SCORE;
    }

    @Override
    public Field<String> field3() {
        return Transactions.TRANSACTIONS.CODE;
    }

    @Override
    public Field<String> field4() {
        return Transactions.TRANSACTIONS.CARRIER_USERNAME;
    }

    @Override
    public Field<String> field5() {
        return Transactions.TRANSACTIONS.REQUEST_CODE;
    }

    @Override
    public Field<String> field6() {
        return Transactions.TRANSACTIONS.OFFER_CODE;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Transactions.TRANSACTIONS.PERFORM_TIME;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Transactions.TRANSACTIONS.CREATED_AT;
    }

    @Override
    public Field<UUID> field9() {
        return Transactions.TRANSACTIONS.CREATED_BY;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public Short component2() {
        return getScore();
    }

    @Override
    public String component3() {
        return getCode();
    }

    @Override
    public String component4() {
        return getCarrierUsername();
    }

    @Override
    public String component5() {
        return getRequestCode();
    }

    @Override
    public String component6() {
        return getOfferCode();
    }

    @Override
    public LocalDateTime component7() {
        return getPerformTime();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public UUID component9() {
        return getCreatedBy();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public Short value2() {
        return getScore();
    }

    @Override
    public String value3() {
        return getCode();
    }

    @Override
    public String value4() {
        return getCarrierUsername();
    }

    @Override
    public String value5() {
        return getRequestCode();
    }

    @Override
    public String value6() {
        return getOfferCode();
    }

    @Override
    public LocalDateTime value7() {
        return getPerformTime();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public UUID value9() {
        return getCreatedBy();
    }

    @Override
    public TransactionsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public TransactionsRecord value2(Short value) {
        setScore(value);
        return this;
    }

    @Override
    public TransactionsRecord value3(String value) {
        setCode(value);
        return this;
    }

    @Override
    public TransactionsRecord value4(String value) {
        setCarrierUsername(value);
        return this;
    }

    @Override
    public TransactionsRecord value5(String value) {
        setRequestCode(value);
        return this;
    }

    @Override
    public TransactionsRecord value6(String value) {
        setOfferCode(value);
        return this;
    }

    @Override
    public TransactionsRecord value7(LocalDateTime value) {
        setPerformTime(value);
        return this;
    }

    @Override
    public TransactionsRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TransactionsRecord value9(UUID value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public TransactionsRecord values(UUID value1, Short value2, String value3, String value4, String value5, String value6, LocalDateTime value7, LocalDateTime value8, UUID value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionsRecord
     */
    public TransactionsRecord() {
        super(Transactions.TRANSACTIONS);
    }

    /**
     * Create a detached, initialised TransactionsRecord
     */
    public TransactionsRecord(UUID id, Short score, String code, String carrierUsername, String requestCode, String offerCode, LocalDateTime performTime, LocalDateTime createdAt, UUID createdBy) {
        super(Transactions.TRANSACTIONS);

        setId(id);
        setScore(score);
        setCode(code);
        setCarrierUsername(carrierUsername);
        setRequestCode(requestCode);
        setOfferCode(offerCode);
        setPerformTime(performTime);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }
}
