/*
 * This file is generated by jOOQ.
 */
package demo.delivery_project.jooq.tables;


import demo.delivery_project.jooq.Keys;
import demo.delivery_project.jooq.Public;
import demo.delivery_project.jooq.tables.records.OffersRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Offers extends TableImpl<OffersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.offers</code>
     */
    public static final Offers OFFERS = new Offers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OffersRecord> getRecordType() {
        return OffersRecord.class;
    }

    /**
     * The column <code>public.offers.id</code>.
     */
    public final TableField<OffersRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.offers.product_id</code>.
     */
    public final TableField<OffersRecord, UUID> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.offers.code</code>.
     */
    public final TableField<OffersRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.offers.place_name</code>.
     */
    public final TableField<OffersRecord, String> PLACE_NAME = createField(DSL.name("place_name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.offers.status</code>.
     */
    public final TableField<OffersRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(32).defaultValue(DSL.field(DSL.raw("'OPEN'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.offers.created_at</code>.
     */
    public final TableField<OffersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.offers.created_by</code>.
     */
    public final TableField<OffersRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID.nullable(false), this, "");

    private Offers(Name alias, Table<OffersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Offers(Name alias, Table<OffersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.offers</code> table reference
     */
    public Offers(String alias) {
        this(DSL.name(alias), OFFERS);
    }

    /**
     * Create an aliased <code>public.offers</code> table reference
     */
    public Offers(Name alias) {
        this(alias, OFFERS);
    }

    /**
     * Create a <code>public.offers</code> table reference
     */
    public Offers() {
        this(DSL.name("offers"), null);
    }

    public <O extends Record> Offers(Table<O> child, ForeignKey<O, OffersRecord> key) {
        super(child, key, OFFERS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OffersRecord> getPrimaryKey() {
        return Keys.OFFERS_PKEY;
    }

    @Override
    public List<UniqueKey<OffersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.OFFERS_CODE_KEY);
    }

    @Override
    public List<ForeignKey<OffersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.OFFERS__OFFERS_PRODUCT_ID_FKEY, Keys.OFFERS__OFFERS_PLACE_NAME_FKEY, Keys.OFFERS__OFFERS_CREATED_BY_FKEY);
    }

    private transient Products _products;
    private transient Places _places;
    private transient Users _users;

    /**
     * Get the implicit join path to the <code>public.products</code> table.
     */
    public Products products() {
        if (_products == null)
            _products = new Products(this, Keys.OFFERS__OFFERS_PRODUCT_ID_FKEY);

        return _products;
    }

    /**
     * Get the implicit join path to the <code>public.places</code> table.
     */
    public Places places() {
        if (_places == null)
            _places = new Places(this, Keys.OFFERS__OFFERS_PLACE_NAME_FKEY);

        return _places;
    }

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.OFFERS__OFFERS_CREATED_BY_FKEY);

        return _users;
    }

    @Override
    public Offers as(String alias) {
        return new Offers(DSL.name(alias), this);
    }

    @Override
    public Offers as(Name alias) {
        return new Offers(alias, this);
    }

    @Override
    public Offers as(Table<?> alias) {
        return new Offers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Offers rename(String name) {
        return new Offers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Offers rename(Name name) {
        return new Offers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Offers rename(Table<?> name) {
        return new Offers(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, UUID, String, String, String, LocalDateTime, UUID> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
