/*
 * This file is generated by jOOQ.
 */
package demo.delivery_project.jooq.tables;


import demo.delivery_project.jooq.Keys;
import demo.delivery_project.jooq.Public;
import demo.delivery_project.jooq.tables.records.RegionsRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Regions extends TableImpl<RegionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.regions</code>
     */
    public static final Regions REGIONS = new Regions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RegionsRecord> getRecordType() {
        return RegionsRecord.class;
    }

    /**
     * The column <code>public.regions.id</code>.
     */
    public final TableField<RegionsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.regions.name</code>.
     */
    public final TableField<RegionsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.regions.is_deleted</code>.
     */
    public final TableField<RegionsRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private Regions(Name alias, Table<RegionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Regions(Name alias, Table<RegionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.regions</code> table reference
     */
    public Regions(String alias) {
        this(DSL.name(alias), REGIONS);
    }

    /**
     * Create an aliased <code>public.regions</code> table reference
     */
    public Regions(Name alias) {
        this(alias, REGIONS);
    }

    /**
     * Create a <code>public.regions</code> table reference
     */
    public Regions() {
        this(DSL.name("regions"), null);
    }

    public <O extends Record> Regions(Table<O> child, ForeignKey<O, RegionsRecord> key) {
        super(child, key, REGIONS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<RegionsRecord> getPrimaryKey() {
        return Keys.REGIONS_PKEY;
    }

    @Override
    public List<UniqueKey<RegionsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.REGIONS_NAME_KEY);
    }

    @Override
    public Regions as(String alias) {
        return new Regions(DSL.name(alias), this);
    }

    @Override
    public Regions as(Name alias) {
        return new Regions(alias, this);
    }

    @Override
    public Regions as(Table<?> alias) {
        return new Regions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Regions rename(String name) {
        return new Regions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Regions rename(Name name) {
        return new Regions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Regions rename(Table<?> name) {
        return new Regions(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super UUID, ? super String, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super UUID, ? super String, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
