/*
 * This file is generated by jOOQ.
 */
package demo.delivery_project.jooq.tables;


import demo.delivery_project.jooq.Indexes;
import demo.delivery_project.jooq.Keys;
import demo.delivery_project.jooq.Public;
import demo.delivery_project.jooq.tables.records.RolePermissionsRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePermissions extends TableImpl<RolePermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.role_permissions</code>
     */
    public static final RolePermissions ROLE_PERMISSIONS = new RolePermissions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RolePermissionsRecord> getRecordType() {
        return RolePermissionsRecord.class;
    }

    /**
     * The column <code>public.role_permissions.role_id</code>.
     */
    public final TableField<RolePermissionsRecord, UUID> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.role_permissions.permission</code>.
     */
    public final TableField<RolePermissionsRecord, String> PERMISSION = createField(DSL.name("permission"), SQLDataType.VARCHAR.nullable(false), this, "");

    private RolePermissions(Name alias, Table<RolePermissionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private RolePermissions(Name alias, Table<RolePermissionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.role_permissions</code> table reference
     */
    public RolePermissions(String alias) {
        this(DSL.name(alias), ROLE_PERMISSIONS);
    }

    /**
     * Create an aliased <code>public.role_permissions</code> table reference
     */
    public RolePermissions(Name alias) {
        this(alias, ROLE_PERMISSIONS);
    }

    /**
     * Create a <code>public.role_permissions</code> table reference
     */
    public RolePermissions() {
        this(DSL.name("role_permissions"), null);
    }

    public <O extends Record> RolePermissions(Table<O> child, ForeignKey<O, RolePermissionsRecord> key) {
        super(child, key, ROLE_PERMISSIONS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ROLE_PERMISSIONS_ROLE_ID_PERMISSION_IDX);
    }

    @Override
    public List<ForeignKey<RolePermissionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ROLE_PERMISSIONS__ROLE_PERMISSIONS_ROLE_ID_FKEY);
    }

    private transient Roles _roles;

    /**
     * Get the implicit join path to the <code>public.roles</code> table.
     */
    public Roles roles() {
        if (_roles == null)
            _roles = new Roles(this, Keys.ROLE_PERMISSIONS__ROLE_PERMISSIONS_ROLE_ID_FKEY);

        return _roles;
    }

    @Override
    public RolePermissions as(String alias) {
        return new RolePermissions(DSL.name(alias), this);
    }

    @Override
    public RolePermissions as(Name alias) {
        return new RolePermissions(alias, this);
    }

    @Override
    public RolePermissions as(Table<?> alias) {
        return new RolePermissions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RolePermissions rename(String name) {
        return new RolePermissions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RolePermissions rename(Name name) {
        return new RolePermissions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RolePermissions rename(Table<?> name) {
        return new RolePermissions(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super UUID, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super UUID, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
