/*
 * This file is generated by jOOQ.
 */
package demo.delivery_project.jooq;


import demo.delivery_project.jooq.tables.FlywaySchemaHistory;
import demo.delivery_project.jooq.tables.Products;
import demo.delivery_project.jooq.tables.RolePermissions;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index PRODUCTS_CREATED_BY_CODE_IDX = Internal.createIndex(DSL.name("products_created_by_code_idx"), Products.PRODUCTS, new OrderField[] { Products.PRODUCTS.CREATED_BY, Products.PRODUCTS.CODE }, true);
    public static final Index PRODUCTS_CREATED_BY_NAME_IDX = Internal.createIndex(DSL.name("products_created_by_name_idx"), Products.PRODUCTS, new OrderField[] { Products.PRODUCTS.CREATED_BY, Products.PRODUCTS.NAME }, true);
    public static final Index ROLE_PERMISSIONS_ROLE_ID_PERMISSION_IDX = Internal.createIndex(DSL.name("role_permissions_role_id_permission_idx"), RolePermissions.ROLE_PERMISSIONS, new OrderField[] { RolePermissions.ROLE_PERMISSIONS.ROLE_ID, RolePermissions.ROLE_PERMISSIONS.PERMISSION }, true);
}
