/*
 * This file is generated by jOOQ.
 */
package demo.delivery_project.jooq;


import demo.delivery_project.jooq.tables.AccessTokens;
import demo.delivery_project.jooq.tables.CarrierRegions;
import demo.delivery_project.jooq.tables.FlywaySchemaHistory;
import demo.delivery_project.jooq.tables.Images;
import demo.delivery_project.jooq.tables.Offers;
import demo.delivery_project.jooq.tables.PgpArmorHeaders;
import demo.delivery_project.jooq.tables.Places;
import demo.delivery_project.jooq.tables.Products;
import demo.delivery_project.jooq.tables.Regions;
import demo.delivery_project.jooq.tables.Requests;
import demo.delivery_project.jooq.tables.RolePermissions;
import demo.delivery_project.jooq.tables.Roles;
import demo.delivery_project.jooq.tables.Transactions;
import demo.delivery_project.jooq.tables.Users;
import demo.delivery_project.jooq.tables.records.PgpArmorHeadersRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.access_tokens</code>.
     */
    public final AccessTokens ACCESS_TOKENS = AccessTokens.ACCESS_TOKENS;

    /**
     * The table <code>public.carrier_regions</code>.
     */
    public final CarrierRegions CARRIER_REGIONS = CarrierRegions.CARRIER_REGIONS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.images</code>.
     */
    public final Images IMAGES = Images.IMAGES;

    /**
     * The table <code>public.offers</code>.
     */
    public final Offers OFFERS = Offers.OFFERS;

    /**
     * The table <code>public.pgp_armor_headers</code>.
     */
    public final PgpArmorHeaders PGP_ARMOR_HEADERS = PgpArmorHeaders.PGP_ARMOR_HEADERS;

    /**
     * Call <code>public.pgp_armor_headers</code>.
     */
    public static Result<PgpArmorHeadersRecord> PGP_ARMOR_HEADERS(
          Configuration configuration
        , String __1
    ) {
        return configuration.dsl().selectFrom(demo.delivery_project.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        )).fetch();
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          String __1
    ) {
        return demo.delivery_project.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          Field<String> __1
    ) {
        return demo.delivery_project.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * The table <code>public.places</code>.
     */
    public final Places PLACES = Places.PLACES;

    /**
     * The table <code>public.products</code>.
     */
    public final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>public.regions</code>.
     */
    public final Regions REGIONS = Regions.REGIONS;

    /**
     * The table <code>public.requests</code>.
     */
    public final Requests REQUESTS = Requests.REQUESTS;

    /**
     * The table <code>public.role_permissions</code>.
     */
    public final RolePermissions ROLE_PERMISSIONS = RolePermissions.ROLE_PERMISSIONS;

    /**
     * The table <code>public.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.transactions</code>.
     */
    public final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AccessTokens.ACCESS_TOKENS,
            CarrierRegions.CARRIER_REGIONS,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Images.IMAGES,
            Offers.OFFERS,
            PgpArmorHeaders.PGP_ARMOR_HEADERS,
            Places.PLACES,
            Products.PRODUCTS,
            Regions.REGIONS,
            Requests.REQUESTS,
            RolePermissions.ROLE_PERMISSIONS,
            Roles.ROLES,
            Transactions.TRANSACTIONS,
            Users.USERS
        );
    }
}
