/*
 * This file is generated by jOOQ.
 */
package demo.delivery_project.jooq;


import demo.delivery_project.jooq.tables.AccessTokens;
import demo.delivery_project.jooq.tables.CarrierRegions;
import demo.delivery_project.jooq.tables.FlywaySchemaHistory;
import demo.delivery_project.jooq.tables.Images;
import demo.delivery_project.jooq.tables.Offers;
import demo.delivery_project.jooq.tables.PgpArmorHeaders;
import demo.delivery_project.jooq.tables.Places;
import demo.delivery_project.jooq.tables.Products;
import demo.delivery_project.jooq.tables.Regions;
import demo.delivery_project.jooq.tables.Requests;
import demo.delivery_project.jooq.tables.RolePermissions;
import demo.delivery_project.jooq.tables.Roles;
import demo.delivery_project.jooq.tables.Transactions;
import demo.delivery_project.jooq.tables.Users;
import demo.delivery_project.jooq.tables.records.PgpArmorHeadersRecord;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.access_tokens</code>.
     */
    public static final AccessTokens ACCESS_TOKENS = AccessTokens.ACCESS_TOKENS;

    /**
     * The table <code>public.carrier_regions</code>.
     */
    public static final CarrierRegions CARRIER_REGIONS = CarrierRegions.CARRIER_REGIONS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.images</code>.
     */
    public static final Images IMAGES = Images.IMAGES;

    /**
     * The table <code>public.offers</code>.
     */
    public static final Offers OFFERS = Offers.OFFERS;

    /**
     * The table <code>public.pgp_armor_headers</code>.
     */
    public static final PgpArmorHeaders PGP_ARMOR_HEADERS = PgpArmorHeaders.PGP_ARMOR_HEADERS;

    /**
     * Call <code>public.pgp_armor_headers</code>.
     */
    public static Result<PgpArmorHeadersRecord> PGP_ARMOR_HEADERS(
          Configuration configuration
        , String __1
    ) {
        return configuration.dsl().selectFrom(demo.delivery_project.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        )).fetch();
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          String __1
    ) {
        return demo.delivery_project.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          Field<String> __1
    ) {
        return demo.delivery_project.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * The table <code>public.places</code>.
     */
    public static final Places PLACES = Places.PLACES;

    /**
     * The table <code>public.products</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>public.regions</code>.
     */
    public static final Regions REGIONS = Regions.REGIONS;

    /**
     * The table <code>public.requests</code>.
     */
    public static final Requests REQUESTS = Requests.REQUESTS;

    /**
     * The table <code>public.role_permissions</code>.
     */
    public static final RolePermissions ROLE_PERMISSIONS = RolePermissions.ROLE_PERMISSIONS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.transactions</code>.
     */
    public static final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
